export const BUTTON_MODE={
    SUCCESS:{
        BG_PARENT:'#459724',
        BG_BUTTON:'#58bd2f',
        COLOR:'#FFF'
    },
    WARNING:'WARNING',
    DANGER:'DANGER',
    DISABLED:{
        BG_PARENT:'#828282',
        BG_BUTTON:'#828282',
        COLOR:'#FFF'
    },
    PRIMARY:{
        BG_PARENT:'#e5e5e5',
        BG_BUTTON:'#FFF',
        COLOR:'#000'
    }
}